MathoosHouse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('money/', include('MyMoney.urls')),
    path('users/', include('Users.urls')),
    path('webhooks/', include('Notifications.urls')),
]


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

MyMoney/urls.py
from django.urls import path

from MyMoney import views

app_name = "MyMoney"

urlpatterns = [
    path("<gid>/balance/", views.show_balance, name="balance"),
    path("<gid>/expense/new/", views.new_expense, name="new-expense"),
    path("<gid>/expense/<pk>/edit", views.edit_expense, name="edit-expense"),
    path("<gid>/expense/<pk>/delete", views.delete_expense, name="delete-expense"),
    path("<gid>/expense/history/", views.index_expense, name="index-expense"),
    path("<gid>/repay/<user1>/<user2>", views.rembourser, name="rembourser"),
]

Notifications/urls.py
from django.urls import path

from Notifications.views import CreateWebhook, DeleteWebhook

app_name = "Notifications"

urlpatterns = [
    path("<int:webhook_id>/delete/", DeleteWebhook.as_view(), name="delete"),
    path("new/", CreateWebhook.as_view(), name="create"),
]

Thunes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('money/', include('MyMoney.urls')),
    path('users/', include('Users.urls')),
    path('api/', include('api.urls')),
]

if "Notifications" in settings.INSTALLED_APPS:
    urlpatterns.append(path('webhooks/', include('Notifications.urls')))



if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework'))  ,  
]

MyMoney/models.py
from django.db import models
from django.contrib.auth.models import User, Group


class Currency(models.Model):
    name = models.CharField(max_length=3)
    symbol = models.CharField(max_length=1, null=True, blank=True)
    value_in_eur = models.DecimalField(decimal_places=2, max_digits=10)

    class Meta:
        verbose_name = 'currency'
        verbose_name_plural = 'currencies'

    def __str__(self):
        return "{} ({})".format(self.name, self.symbol)

class Expense(models.Model):
    name = models.CharField(max_length=50)
    origin = models.ForeignKey(User, on_delete=models.PROTECT)
    group = models.ForeignKey(Group, on_delete=models.PROTECT)
    description = models.TextField(blank=True)
    value = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)
    date = models.DateField(blank=True)

    def __str__(self):
        return "{}-{} ({}) {} {}".format(self.group, self.name, self.origin, self.value, self.currency)

    def delete(self, *args, **kwargs):
        shares = self.share_set.all()
        for share in shares:
            share.delete()
        super().delete(*args, **kwargs)

class Share(models.Model):
    value = models.DecimalField(decimal_places=2, max_digits=10)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    expense = models.ForeignKey(Expense, on_delete=models.PROTECT)

    def __str__(self):
        return "{} {}".format(self.owner, self.value)

MyMoney/forms.py
from django import forms
from django.contrib.auth.models import User, Group

import MyMoney.models as models

from bootstrap_datepicker_plus.widgets import DatePickerInput

from django.core.exceptions import ValidationError

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = models.Expense
        fields = '__all__'
        widgets = {
            'date': DatePickerInput(format='%m/%d/%Y'),
        }

    def __init__(self, *args, **kwargs):
        group = kwargs.pop('group', None)
        super(ExpenseForm, self).__init__(*args, **kwargs)
        self.fields['origin'].queryset = group.user_set.all()
        self.fields['group'].required = False
        self.fields['group'].widget = forms.HiddenInput()

class ShareForm(forms.ModelForm):
    class Meta:
        model = models.Share
        fields = [
            'value',
            'owner',
            ]

MyMoney/views.py
from fractions import Fraction

from django.apps import apps
from django.urls import reverse
from django.utils import timezone
from django.core.cache import cache
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory, formset_factory
from django.db import transaction
from django.db.models import Sum

import MyMoney.forms as forms
import MyMoney.models as models

from Users.models import Group

from .algo import balance_transactions

from DjangoTools.decorators import (
    check_group,
)

from .forms import (
    ExpenseForm,
    ShareForm,
)

if apps.is_installed("Notifications"):
    from Notifications.models import DiscordWebhook
    from Notifications.forms import WebhookForm
    from Notifications.utils import send_notification


@login_required
@check_group()
def show_balance(request, gid):
    group = Group.objects.get(id=gid)

    users_balance_key = f"show_balance_{gid}_user_balance"
    transactions_key = f"show_balance_{gid}_transactions"
    users_balance = cache.get(users_balance_key)
    transactions = cache.get(transactions_key)

    if users_balance is None or transactions is None:
        users = get_user_model().objects.filter(groups=group)
        expenses = models.Expense.objects.filter(group=group)
        users_balance = {}

        for user in users:
            users_balance[user.username] = 0
            # User.username est une clef unique, on peut indexer sans soucis dessus

        for expense in expenses:
            shares = expense.share_set
            value = Fraction(
                int(expense.value * expense.currency.value_in_eur * 100), 100
            )
            sum_shares = int(shares.aggregate(total=Sum("value")).get("total") * 100)

            users_balance[expense.origin.username] += value
            for user in users:
                share = shares.filter(owner=user)
                if share:  # Si la share d'un user n'existe pas, elle vaut 0, on ignore
                    share = int(share.get().value * 100)
                    users_balance[user.username] -= value * Fraction(share, sum_shares)

        transactions = balance_transactions(users_balance)
        cache.set(users_balance_key, users_balance, None)
        cache.set(transactions_key, transactions, None)
        # Pas de timeout, on invalide manuellement

    context = {
        "balance": users_balance,
        "group": group,
        "transactions": transactions,
    }

    if apps.is_installed("Notifications") and request.user.is_staff:
        context["notifications"] = True
        context["hooks"] = DiscordWebhook.objects.filter(group=group)
        context["hook_form"] = WebhookForm(initial={"group": group})
    else:
        context["notifications"] = False

    return render(request, "balance.html", context)


@login_required
@check_group()
def new_expense(request, gid):
    group = Group.objects.get(id=gid)
    n = group.user_set.count()
    if n == 0:
        raise Exception
    currency, _ = models.Currency.objects.get_or_create(
        name="Eur", defaults={"value_in_eur": 1, "symbol": "€"}
    )
    expense_form = ExpenseForm(
        request.POST or None,
        group=group,
        initial={"origin": request.user, "currency": currency},
    )

    # On crée des parts à 0 pour tous les membres du groupe
    ShareFormSet = formset_factory(ShareForm, extra=0)
    share_formset = ShareFormSet(request.POST or None)

    if expense_form.is_valid() and share_formset.is_valid():
        with transaction.atomic():
            expense = expense_form.save(commit=False)
            expense.group = group
            if not expense.date:
                expense.date = timezone.now()
            expense.save()

            for share_form in share_formset:
                share = share_form.save(commit=False)
                share.expense = expense
                share.save()

        if apps.is_installed("Notifications"):
            send_notification(expense)

        return redirect(reverse("MyMoney:balance", kwargs={"gid": gid}))

    elif request.method != "GET":
        return render(
            request,
            "expense.html",
            {
                "expense_form": expense_form,
                "share_formset": share_formset,
                "group": group,
            },
        )

    else:
        initial_share = []
        for user in group.user_set.all():
            initial_share.append({"value": 1, "owner": user})
            share_formset = ShareFormSet(initial=initial_share)

        return render(
            request,
            "expense.html",
            {
                "expense_form": expense_form,
                "share_formset": share_formset,
                "group": group,
            },
        )


@login_required
@check_group()
def edit_expense(request, gid, pk):
    """Edite une dépense"""
    group = Group.objects.get(id=gid)
    expense = get_object_or_404(models.Expense, id=pk)
    expense_form = ExpenseForm(request.POST or None, group=group, instance=expense)
    ShareFormSet = modelformset_factory(
        models.Share, fields=("value", "owner"), extra=0
    )
    share_formset = ShareFormSet(request.POST or None, queryset=expense.share_set.all())

    old_value = expense.value
    old_shares = {}
    for share in expense.share_set.all():
        old_shares[share.owner.username] = share.value

    if expense_form.is_valid() and share_formset.is_valid():
        with transaction.atomic():
            expense = expense_form.save(commit=False)
            expense.group = group
            if not expense.date:
                expense.date = timezone.now()
            expense.save()

            for share_form in share_formset:
                share = share_form.save(commit=False)
                share.expense = expense
                share.save()

        send_notification(
            expense, change=True, old_shares=old_shares, old_value=old_value
        )

        return redirect(reverse("MyMoney:index-expense", kwargs={"gid": gid}))

    return render(
        request,
        "expense.html",
        {
            "expense_form": expense_form,
            "share_formset": share_formset,
            "group": group,
        },
    )


@login_required
@check_group()
def delete_expense(request, gid, pk):
    """Supprime une dépense"""
    expense = get_object_or_404(models.Expense, id=pk)
    expense.delete()

    return redirect(reverse("MyMoney:index-expense", kwargs={"gid": gid}))


@login_required
@check_group()
def index_expense(request, gid):
    """Affiche l'historique des dépenses d'un groupe"""
    group = Group.objects.get(id=gid)
    expenses_key = f"index_expense_{gid}_expenses"
    totalshare_key = f"index_expense_{gid}_totalshare"

    expenses = cache.get(expenses_key)
    totalshare = cache.get(totalshare_key)

    if expenses is None or totalshare is None:
        expenses = models.Expense.objects.filter(group=group).order_by("-date", "-id")
        shares = [expense.share_set.all() for expense in expenses]
        totalshare = [sum([share.value for share in queryset]) for queryset in shares]

        cache.set(expenses_key, expenses, None)
        cache.set(totalshare_key, totalshare, None)

    return render(
        request,
        "index_expenses.html",
        {
            "expense_total": zip(expenses, totalshare),
            "group": group,
            "gid": gid,
        },
    )


@login_required
@check_group()
def rembourser(request, gid, user1, user2):
    group = Group.objects.get(id=gid)
    user1 = User.objects.get(username=user1)
    user2 = User.objects.get(username=user2)
    n = group.user_set.count()
    if n == 0:
        raise Exception

    if request.method == "GET":
        ShareFormSet = formset_factory(ShareForm, extra=0)

        initial_expense = {"name": "Remboursement", "origin": user1}
        expense_form = ExpenseForm(group=group, initial=initial_expense)

        # On crée une part à -1 pour l'user2, et à 0 pour le reste
        initial_share = [{"value": -1, "owner": user2}]

        for user in group.user_set.exclude(username=user2.username):
            initial_share.append({"value": 0, "owner": user})

        share_formset = ShareFormSet(initial=initial_share)

        return render(
            request,
            "expense.html",
            {
                "expense_form": expense_form,
                "share_formset": share_formset,
                "group": group,
            },
        )

    else:
        expense_form = ExpenseForm(request.POST or None, group=group)

        ShareFormSet = formset_factory(ShareForm, extra=0)
        share_formset = ShareFormSet(request.POST or None)

        if expense_form.is_valid():
            if share_formset.is_valid():
                expense = expense_form.save(commit=False)
                expense.group = group
                expense.save()

                for share_form in share_formset:
                    share = share_form.save(commit=False)
                    share.expense = expense
                    share.save()

                return redirect(reverse("MyMoney:balance", kwargs={"gid": gid}))

        else:
            return render(
                request,
                "expense.html",
                {
                    "expense_form": expense_form,
                    "share_formset": share_formset,
                    "group": group,
                },
            )

MyMoney/templates/balance.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load bootstrap_icons %}
{% block title %} Balance {% endblock %}

{% block content %}
<h2>Finances du groupe {{group.name}}</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Utilisateur</td>
      <td>Solde</td>
    </tr>
  </thead>
  {% for username, solde in balance.items %}
    <tr>
      <td><a href="">{{ username }}</a></td>
      <td>{{ solde | floatformat:2 }} €</td>
    </tr>
  {% endfor %}
</table>

<a href="{% url "MyMoney:new-expense" group.id %}">
  {% bootstrap_button "Nouvelle dépense" button_type="link" %}
</a>
<a href="{% url "MyMoney:index-expense" group.id %}">
  {% bootstrap_button "Historique des dépenses" button_type="link" %}
</a>

<h2>Remboursements</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Transaction</td>
      <td>Montant</td>
      <td>Action</td>
    </tr>
  </thead>
  {% for trans in transactions %}
  {% if trans.2 > 0.005 %}
  <tr>
    <td>
      <a href="">{{ trans.0 }}</a>
      {% bs_icon 'arrow-right' %}
      <a href="">{{ trans.1 }}</a>
    </td>
    <td>
      {{ trans.2|floatformat:2 }} €
    </td>
    <td>
      <a href="{% url "MyMoney:rembourser" group.id trans.0 trans.1 %}">
        {% bootstrap_button "Rembourser" button_type="link" %}
      </a>
    </td>
  </tr>
  {% endif %}
  {% endfor %}
</table>

{% if notifications %}
<h2>Notifications</h2>
<table class="table table-striped">
  {% for hook in hooks %}
  <tr>
    <td>
      {{ hook.name }}
    </td>
    <td>
      <small><span class="text-muted">https://discord.com/api/webhooks/</span><strong>{{ hook.snowflake }}</strong><span class="text-muted">/</span><strong>{{ hook.token }}</strong></small>
    </td>
    <td>
      <form action="{% url "Notifications:delete" hook.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="btn btn-danger"></input>
      </form>
    </td>
  </tr>
  {% endfor %}
</table>
<form action="{% url "Notifications:create" %}" method="post">
  {% csrf_token %}
  {% bootstrap_form hook_form layout="horizontal" %}
  <input type="submit" value="Nouveau" class="btn btn-primary"></input>
</form>
{% endif %}
{% endblock %}

MyMoney/templates/expense.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% load static %}


{% block title %}Ajouter une dépense{% endblock %}

{% block content %}
<h2>Ajouter une dépense pour le groupe {{group.name}} </h2>

<form class="form" method="post">
{{ expense_form.media }}
{% bootstrap_form_errors expense_form %}
{% bootstrap_form expense_form %}



{% csrf_token %}
{% bootstrap_formset_errors share_formset %}

<h2> Shares : </h2>
{{ share_formset.management_form }}

<div class="row">
  {% for share in share_formset.forms %}
  <tr>
    <!-- <p>Part de {{ share.owner.get_username }} </p> -->
    <div class="col-xs-12 col-sm-4 col-md-3" style="margin-top:1em">
      {% bootstrap_form share  %}
    </div>
  </tr>
  {% endfor %}
</div>

{% bootstrap_button "Submit" button_type="submit" button_class='btn-success' %}
</form>

{% endblock %}

MyMoney/templates/favorite_expenses.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}Dépenses favorites de {{group}} {% endblock %}

{% block content %}
<h2>Dépenses favorites de {{group}}</h2>
<a href="{% url "MyMoney:balance" gid %}"> {% bootstrap_button "Retour au groupe" button_type="link" %} </a>
<div >
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Nom</th>
      <th>Emetteur</th>
      <th>Description</th>
      <th>Valeur</th>
      <th>Devise</th>
      <th>Parts</th>
    </tr>
    </thead>
    {% for expense in expense_list %}
    <tr>
      <td>{{ expense.date }}</td>
      <td>{{ expense.name }}</td>
      <td>{{ expense.origin }}</td>
      <td>{{ expense.description }}</td>
      <td>{{ expense.value }}</td>
      <td>{{ expense.currency }}</td>
      <td>{% for share in expense.share_set.all %}
	<li>{{ share.owner }} : {{ share.value }} </li>
	{% endfor %}
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

MyMoney/templates/index_expenses.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load static %}
{% load mathfilters %}




{% block title %}Historique des dépenses de {{ group }} {% endblock %}

{% block content %}

<style type="text/css">
  .table-nostriped tbody tr:nth-of-type(odd) {
      background-color:transparent;
  }

  div.scrollable {
      word-wrap: break-word;
      max-width: 160px;
      max-height: 160px;
      margin: 0;
      padding: 0;
      overflow: auto;
  }
</style>


<h2>Historique des dépenses de {{group}}</h2>
<a href="{% url "MyMoney:balance" gid %}"> {% bootstrap_button "Retour au groupe" button_type="link" %} </a>
  <table class="table-responsive table-striped display" id="1">
    <thead>
    <tr>
      <th>Date</th>
      <th class="text-center">Nom</th>
      <th>Emetteur</th>
      <th>Description</th>
      <th>Valeur</th>
      <th class="text-center">Parts</th>
      <th/>
    </tr>
    </thead>
    <tbody>
    {% for expense, total in expense_total %}
    <tr>
      <td class="text-nowrap">{{ expense.date }}</td>
      <td><div class="scrollable">{{ expense.name }}</div></td>
      <td>{{ expense.origin }}</td>
      <td><div class="scrollable">{{ expense.description | safe}}</div></td>
      <td class="text-nowrap">{{ expense.value }} {{ expense.currency.symbol }}</td>
      <td class="text-nowrap">
	<div class="table-responsive">
	  <table class="table-borderless table-nostriped">
	    <tbody>
	      {% for share in expense.share_set.all %}
	      <tr>
		{% if share.value != 0 %}
		<td>{{ share.owner }}</td>
		<td class="text-nowrap">
		  {{ expense.value | mul:share.value|div:total | floatformat:2}}
		  {{ expense.currency.symbol }}
		</td>
		<td>({{ share.value }})</td>
		{% endif %}
		{% endfor %}
	      </tr>
	    </tbody>
	  </table>
	</div>
      </td>
      <td>
	<a href="{% url "MyMoney:edit-expense" gid expense.id %}"> {% bootstrap_button "Modifier" button_type="link" button_class="btn-success btn-block" %}
	</a>
	<a href="{% url "MyMoney:delete-expense" gid expense.id %}"> {% bootstrap_button "Supprimer" button_type="link" button_class="btn-danger btn-block" %}
	</a>
      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

{% block extrascripts %}


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment-with-locales.min.js" defer></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js" defer></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" defer></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js" defer></script>


<script>
  $(document).ready( function () {
      $.fn.dataTable.moment('DD MMMM YYYY', 'fr');
      $('#1').DataTable({
	  stateSave: true,
	  "order": [[ 0, "desc" ]]
      } );
  } );
</script>
{% endblock %}