MathoosHouse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('money/', include('MyMoney.urls')),
    path('users/', include('Users.urls')),
    path('webhooks/', include('Notifications.urls')),
]


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

MyMoney/urls.py
from django.urls import path

from MyMoney import views

app_name = "MyMoney"

urlpatterns = [
    path("<gid>/balance/", views.show_balance, name="balance"),
    path("<gid>/expense/new/", views.new_expense, name="new-expense"),
    path("<gid>/expense/<pk>/edit", views.edit_expense, name="edit-expense"),
    path("<gid>/expense/<pk>/delete", views.delete_expense, name="delete-expense"),
    path("<gid>/expense/history/", views.index_expense, name="index-expense"),
    path("<gid>/repay/<user1>/<user2>", views.rembourser, name="rembourser"),
]

Thunes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from django.conf import settings

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('money/', include('MyMoney.urls')),
    path('users/', include('Users.urls')),
    path('api/', include('api.urls')),
]

if "Notifications" in settings.INSTALLED_APPS:
    urlpatterns.append(path('webhooks/', include('Notifications.urls')))



if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Users/urls.py
from django.urls import path

from . import views

app_name = "Users"

urlpatterns = [
    path("users/", views.index_users, name='users'),
    path("groups/", views.index_groups, name='groups'),
    path("create/", views.create_user, name="create_user"),
    path("groups/create/", views.create_edit_group, name="create_group"),
    path("groups/edit/<gid>/", views.create_edit_group, name="edit_group"),
    ]

api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework'))  ,  
]

Users/models.py
from django.db import models

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group as DjangoGroup


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    favorite_groups = models.ManyToManyField(
        blank=True, to="Users.Group", related_name="favorite_groups"
    )


class Group(DjangoGroup):
    class Meta:
        proxy = True

Users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Group


class UserCreationFormWithEmail(UserCreationForm):
    email = forms.EmailField(label='Email', required=False)



class GroupCreateOrEditForm(forms.ModelForm):
    """Formulaire de création ou l'édition d'un groupe"""
    def __init__(self, *args, **kwargs):
        super(GroupCreateOrEditForm, self).__init__(*args, **kwargs)
        try:
            self.fields['members'].initial = self.instance.user_set.all()
            self.fields['name'].widget.attrs['readonly'] = 'true'
        except:
            pass
    members = forms.ModelMultipleChoiceField(queryset = get_user_model().objects.all(), widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Group
        fields = ['name',]

Users/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from MyMoney.utils import add_to_group

from .models import (
    Group,
)

from .forms import (
    GroupCreateOrEditForm,
    UserCreationFormWithEmail,
)


@login_required
def create_user(request):
    """Create a new user"""
    if request.method == 'GET':
        form = UserCreationFormWithEmail
        return render(request, 'users/create_user.html', {'form': form})
    elif request.method == 'POST':
        form = UserCreationFormWithEmail(request.POST)
        if form.is_valid():
            username = form['username'].value()
            email = form['email'].value()
            form.save()
            new_user = get_user_model().objects.get(username=username)
            new_user.email = email
            new_user.save()
            return redirect("/")
        else:
            return render(request, 'users/create_user.html', {'form': form})

@login_required
def create_edit_group(request, gid=None):
    """Create a new group"""
    if request.method == 'GET':
        if gid:
            form = GroupCreateOrEditForm(instance=get_object_or_404(Group, id=gid))
        else:
            form = GroupCreateOrEditForm
        return render(request, 'users/create_group.html', {'form': form})
    elif request.method == 'POST':
        if gid:
            form = GroupCreateOrEditForm(request.POST, instance=get_object_or_404(Group, id=gid))
        else:
            form = GroupCreateOrEditForm(request.POST)
        members = request.POST.getlist('members')
        queryset = User.objects.filter(id__in=members)
        if form.is_valid():
            group = form.save()
            if gid:
                old_members = get_object_or_404(Group, id=gid).user_set.all()
                if set(old_members) <=  set(queryset):
                    for u in queryset.difference(old_members):
                        add_to_group(u, group)
                else:
                    form.add_error("members", "Ne retire pas de membres pauvre fou !")
                    return render(request, 'users/create_group.html', {'form': form})
            group.user_set.set(queryset)
            group.save()
            return redirect(reverse(
                'Users:groups',
            ))
        else:
            return render(request, 'users/create_group.html', {'form': form})



@login_required
def index_users(request):
    """Affiche la liste des utilisateurs"""
    users = User.objects.all()
    return render(request, 'users/index_users.html', {'users': users})

@login_required
def index_groups(request):
    """Affiche la liste des groupes de l'utilisateur qui a fait la requête"""
    groups = request.user.groups.all()
    return render(request, 'users/index_groups.html', {'groups': groups})

Users/templates/users/create_group.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %} Groups {% endblock %}

{% block content %}

<form action="" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>

{% endblock %}

Users/templates/users/create_user.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %} Users {% endblock %}

{% block content %}
<div class="container">
  <form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

Users/templates/users/index_groups.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %} Users {% endblock %}

{% block content %}
<h2>Liste des groupes</h2>

<div class="container">
  {% if not groups %}
  <div class="row">
    Vous n'êtes actuellement dans aucun groupe
  </div>
  {% else %}
  <div class="row">
    <div class="table-responsive">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nom du groupe</th>
            <th>Membres</th>
          </tr>
        </thead>
        {% for group in groups %}
        <tr>
          <td>
            <a href="{% url 'MyMoney:balance' group.id %}" class="nav-link"> {{ group.name }}</a>
          </td>
          <td>
            {% if not group.user_set.all %}
            <ul> Ce groupe n'a aucun membre </ul>
            {% else %}
            {% for user in group.user_set.all %}
            <li> {{ user }} </li>
            {% endfor %}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  <div class="row p-2">
    <a class="mx-auto" href="{% url 'Users:create_group' %}"> {% bootstrap_button "Créer un groupe" button_type="link" %} </a>
  </div>
</div>
{% endif %}
{% endblock %}

Users/templates/users/index_users.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %} Users {% endblock %}

{% block content %}
<h2>Liste des utilisateurs</h2>

<div class="container">
  {% if not users %}
  <div class="row">
    Il n'y a encore aucun utilisateur
  </div>
  {% else %}
  <div class="row">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nom d'utilisateur</th>
            <th>Groupes</th>
            <th>Date de création</th>
            <th>Dernière connexion</th>
          </tr>
        </thead>
        {% for user in users %}
        <tr>
          <td>{{ user.username }}</td>
          <td>
            {{ user.groups.all | join:', ' }}
          </td>
          <td>{{ user.date_joined }}</td>
          <td>{{ user.last_login | default:'' }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  <div class="row">
    {% if request.user.is_superuser %}
    <a class="mx-auto" href="{% url 'Users:create_user' %}"> {% bootstrap_button "Créer un utilisateur" button_type="link" %} </a>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}